variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY_USERNAME: loconomics
  CI_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH
  DOCKER_IMAGE_NAME: loconomics/loconomics

stages:
  - build_assets
  - build_backend
  - publish
  - deploy

build assets:
  stage: build_assets
  image: node:9
  script:
  - npm install -g yarn
  - chmod +x /usr/local/bin/yarn
  - git clone https://github.com/loconomics/loconomics
  - rm .eslint*
  - cd loconomics/app
  - yarn
  - yarn build
  artifacts:
    paths:
    - loconomics/app/build
    expire_in: 1 hour

build backend:
  stage: build_backend
  image: docker:latest
  services:
  - docker:dind
  script:
  - cp -R loconomics/app/build/* assets/
  - rm -rf loconomics/
  - docker build -t $CI_IMAGE_NAME .
  - docker tag $CI_IMAGE_NAME $CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  - docker tag $CI_IMAGE_NAME $CI_IMAGE_NAME:$CI_COMMIT_SHA
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_IMAGE_NAME

publish production image:
  stage: publish
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_IMAGE_NAME:master
  - docker tag $CI_IMAGE_NAME:master $DOCKER_IMAGE_NAME:latest
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  - docker push $DOCKER_IMAGE_NAME:latest
  only:
  - master

publish staging image:
  stage: publish
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_IMAGE_NAME:staging
  - docker tag $CI_IMAGE_NAME:master $DOCKER_IMAGE_NAME:staging
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  - docker push $DOCKER_IMAGE_NAME:staging
  only:
  - staging

deploy production image:
  stage: deploy
  image: microsoft/azure-cli
  script:
  - env
  environment:
    name: production
    url: https://www.loconomics.com/
  only:
  - master

deploy staging image:
  stage: deploy
  image: microsoft/azure-cli
  script:
  - env
  # See https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html when ready to set this up.
  # - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  environment:
    name: staging
    url: https://staging.loconomics.com/
  only:
  - staging
