variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY_USERNAME: loconomics
  IMAGE_TAG: loconomics/backend

stages:
  - build_assets
  - build_backend
  - publish

build assets:
  stage: build_assets
  image: node:9
  script:
  - npm install -g yarn
  - chmod +x /usr/local/bin/yarn
  - git clone https://github.com/loconomics/loconomics
  - rm .eslint*
  - cd loconomics/app
  - yarn
  - yarn build
  artifacts:
    paths:
    - loconomics/app/build
    expire_in: 1 hour

build backend:
  stage: build_backend
  image: docker:latest
  services:
  - docker:dind
  script:
  - cp -R loconomics/app/build/* assets/
  - rm -rf loconomics/
  - docker build -t $IMAGE_TAG .
  - docker save $IMAGE_TAG -o image.tar
  artifacts:
    paths:
    - image.tar
    expire_in: 1 hour

publish docker image:
  stage: publish
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  - docker load -i image.tar
  only:
  - master
