variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY_USERNAME: loconomics
  CI_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH
  DOCKER_IMAGE_NAME: loconomics/loconomics

stages:
  - build
  - publish
  - deploy

build backend:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG || true
  - docker build -t $CI_IMAGE_NAME .
  - docker tag $CI_IMAGE_NAME $CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  - docker tag $CI_IMAGE_NAME $CI_IMAGE_NAME:$CI_COMMIT_SHA
  - docker push $CI_IMAGE_NAME

publish production image:
  stage: publish
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_IMAGE_NAME:master
  - docker tag $CI_IMAGE_NAME:master $DOCKER_IMAGE_NAME:latest
  - docker tag $CI_IMAGE_NAME:master $DOCKER_IMAGE_NAME:default
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  - docker push $DOCKER_IMAGE_NAME:latest
  - docker push $DOCKER_IMAGE_NAME:default
  only:
  - master

publish staging image:
  stage: publish
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_IMAGE_NAME:staging
  - docker tag $CI_IMAGE_NAME:staging $DOCKER_IMAGE_NAME:staging
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  - docker push $DOCKER_IMAGE_NAME:staging
  only:
  - staging

.deploy production image:
  stage: deploy
  image: microsoft/azure-cli
  script:
  - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  - az webapp restart -g app-staging -n loconomics-staging
  environment:
    name: production
    url: https://www.loconomics.com/
  only:
  - master

deploy staging image:
  stage: deploy
  image: microsoft/azure-cli
  script:
  - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  - az webapp restart -g app-staging -n loconomics-staging
  environment:
    name: staging
    url: http://staging.loconomics.com/
  only:
  - staging
