version: "3"

services:

  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password!!11
    volumes:
      - ./:/host

  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: mssql://sa:Password!!11@db/master
      LOCONOMICS_BACKEND_URL: https://dev.loconomics.com
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/host
    working_dir: /host
    command: sh -c "sleep 5 && yarn dev"
